minVersion: '0.13.2'
github:
    owner: getsentry
    repo: sentry-ruby
changelogPolicy: simple
preReleaseCommand: ruby ../.scripts/bump-version.rb
releaseBranchPrefix: release-sentry-ruby
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
    # we always need to make sure sentry-ruby-core is present when pushing to any target
    - name: gem
      onlyIfPresent: /^sentry-ruby-core-\d.*\.gem$/
    - name: registry
      onlyIfPresent: /^sentry-ruby-core-\d.*\.gem$/
      type: sdk
      config:
          canonical: 'gem:sentry-ruby'
    - name: registry
      onlyIfPresent: /^sentry-ruby-core-\d.*\.gem$/
      type: sdk
      config:
          canonical: 'gem:sentry-ruby-core'
    - name: github
      onlyIfPresent: /^sentry-ruby-core-\d.*\.gem$/
      tagPrefix: sentry-ruby-v
